FROM debian:trixie-slim as install

ARG DEBIAN_FRONTEND=noninteractive

#SHELL ["/bin/bash", "-c"]
RUN rm /bin/sh \
  && ln -s /bin/bash /bin/sh

# install dependencies
RUN apt update && apt upgrade -y \
  && apt install -y --no-install-recommends --no-install-suggests ca-certificates git curl libyaml-dev build-essential libssl-dev zlib1g-dev \
  && rm -rf "/var/lib/apt/lists/*" \
  && rm -rf /var/cache/apt/archives

# add user and set home directory
ARG USER=rails
RUN useradd --create-home --shell /bin/bash $USER
ARG HOME="/home/$USER"
WORKDIR $HOME
USER $USER

# install Ruby, Node.js, Yarn
ENV NODE_VERSION=22.19.0
RUN git clone https://github.com/nvm-sh/nvm.git --depth 1 ~/.nvm \
  && cd .nvm \
  && . $HOME/.nvm/nvm.sh \
  && nvm --version \
  && nvm install $NODE_VERSION \
  && npm --version \
  && npm install --global yarn \
  && which yarn \
  && yarn --version
ENV PATH="$HOME/.nvm/versions/node/v$NODE_VERSION/bin/:$PATH"

# install Ruby using rbenv
ENV PATH="$HOME/.rbenv/bin:$PATH"
RUN git clone https://github.com/rbenv/rbenv.git --depth 1 ~/.rbenv \
  && ~/.rbenv/bin/rbenv init \
  && rbenv --version \
  && mkdir "$(rbenv root)"/plugins/ \
  && git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build \
  && rbenv install 3.4.6 \
  && rbenv global 3.4.6
ENV PATH="$HOME/.rbenv/shims:$PATH"

WORKDIR /rails/demo

# install Rails and initialize a new Rails app
RUN bundle init \
  && bundle add rails --version "~> 8.0.3" \
  && bundle exec rails new . --force --skip-git --api --database=sqlite3 \
  # https://graphql-ruby.org/getting_started.html
  && bundle add graphql graphiql-rails \
  && bundle exec rails generate graphql:install \
  && bundle exec rails generate model HighScore game:string score:integer \
  && RAILS_ENV=production bundle exec rails db:migrate \
  && RAILS_ENV=production bundle exec rails generate graphql:object HighScore game:String score:Int \
  && RAILS_ENV=production bundle exec rails generate graphql:mutation_create HighScore \
  && RAILS_ENV=production bundle exec rails generate graphql:mutation_update HighScore \
  && RAILS_ENV=production bundle exec rails generate graphql:mutation_delete HighScore \
  && bundle exec rails generate graphql:mutation TestMutation \
  && bundle exec rails generate model Post title:string rating:integer comments:text \
  && RAILS_ENV=production bundle exec rails db:migrate \
  && RAILS_ENV=production bundle exec rails generate graphql:object Post title:String rating:Int comments:Text \
  && sed -i 's/# root/mount GraphiQL::Rails::Engine, at: "\/graphiql", graphql_path: "\/graphql"\n  # root/g' config/routes.rb \
  #&& bundle add sprocket-rails \
  && sed -i '1s/^/#require "sprockets\/railtie"\n/' config/application.rb \
  && mkdir -p app/assets/config \
  && echo "//= link graphiql/rails/application.css\n//= link graphiql/rails/application.js" >> app/assets/config/manifest.js

# new stage for Rails app
FROM debian:trixie-slim as rails

# install dependencies
RUN apt update && apt upgrade -y \
  && apt install -y --no-install-recommends --no-install-suggests libyaml-dev libssl-dev \
  && rm -rf "/var/lib/apt/lists/*" \
  && rm -rf /var/cache/apt/archives

# add user and set home directory
ARG USER=rails
RUN useradd --create-home --shell /bin/bash $USER
ARG HOME="/home/$USER"
WORKDIR $HOME
USER $USER

# copy rbenv, Ruby and Rails App from install stage
COPY --from=install $HOME/.rbenv $HOME/.rbenv
ENV PATH="$HOME/.rbenv/shims:$PATH"
COPY --from=install /rails/demo /rails/demo

WORKDIR /rails/demo

ENV RAILS_ENV=production

EXPOSE 3000

HEALTHCHECK --interval=35s --timeout=4s CMD curl -f http://localhost:3000/up || exit 1

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]
